version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/MTM_WIP_Application_WinForms:cached
      - nuget-cache:/workspace/.nuget/packages
    command: sleep infinity
    network_mode: service:db
    depends_on:
      - db
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Server=localhost; Port=3306; Database=mtm_wip_application_winforms_test; Uid=root; Pwd=root; SslMode=none

  db:
    image: mysql:5.7.24
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mtm_wip_application_winforms_test
    volumes:
      - mysql-data:/var/lib/mysql
      - ../Database:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql-data:
  nuget-cache: